### ISSUE TITLE
Premium ACF PRO within public repo

### ISSUE THREAD

**Issue by elliotcondon** [careyestes/careyestes#1]
Hi,

I have just found your public repo that contains my ACF PRO premium plugin.
Can you please remove this repo, or make it private ASAP.

You are currently sharing a premium plugin which violates the terms and conditions you have agreed to.

Thanks
Elliot

**Comment by careyestes** [comment]
Will do Elliot.

My apologies.

**Comment by careyestes** [comment]
Its been removed. I'll run through the rest of my repo to make sure I didn't accidentally push this up in other repos.

**Comment by careyestes** [comment]
It should be gone in all other WP repos. Again, my apologies.
